### ISSUE TITLE
Stable version anytime soon ?

### ISSUE THREAD

**Issue by gregorybesson** [zendframework/zend-developer-tools#204]
Back again about versioning of ZF2 modules :)

Dear @Ocramius, as the 1.0.0-RC1 tagged version has been done beginning of October, and considering we are hundreds (thousands?) of daily users of this module since... years !

It would be formidable if you could create a stable version (1.0 ?)
I fully understand why modules can stay marked as unstable sometimes, but I feel it's also a bad practice when it's too long while many users do use the module and consider it as stable...

Don't you agree ?

(I've already written that somewhere in Github but it's important : Thank you so much @Ocramius Marco Pivetta for the incredibly valuable work you offer to the PHP community day after day for years)

**Comment by samsonasik** [comment]
there is already stable version 1.0.0 and 1.1.0. close-able
