### ISSUE TITLE
Exception on php 7.2

### ISSUE THREAD

**Issue by IgorDePaula** [zendframework/zend-developer-tools#251]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-developer-tools/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-developer-tools/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.
On any route that I navigate, I receive the same exception above:

```Error on line 125, on file  /var/www/html/Project/vendor/zendframework/zend-developer-tools/src/ZendDeveloperTools/Collector/TimeCollector.php: The each() function is deprecated. This message will be suppressed on further calls```.

This occur on php 7.2, ubuntu 18.04

### Code to reproduce the issue

No have code, enable this module and will receive the exceptions

### Expected results

The has no exceptions

### Actual results

Many exceptions

**Comment by webimpress** [comment]
@IgorDePaula What version of zend-developer-tools are you using?
It has been fixed in https://github.com/zendframework/zend-developer-tools/commit/0a0b9f7f9f86094544d07f628e0ebf532076786c and released with 1.2.0.

The latest version is 1.2.1 and I suggest to run composer update to update packages to the latest stable version compatible with PHP 7.2 :)

**Comment by IgorDePaula** [comment]
Sorry, this is a legacy project, and your composer has version 1.0, I'll
update. Thank you very much.

Em sex, 11 de mai de 2018 às 12:29, Michał Bundyra <notifications@github.com>
escreveu:
