### ISSUE TITLE
Zend-Debug has been archived

### ISSUE THREAD

**Issue by dylan-kerr** [zendframework/zend-developer-tools#260]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-developer-tools/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-developer-tools/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

This package depends on Zend-Debug, which has recently been archived and marked as abandoned. This package should either migrate to an alternative or remove the affected funcationality.

It appears there are only two uses of Zend-Debug, both in `view/zend-developer-tools/toolbar/config.phtml`. They could probably be replaced with `var_dump` (wrapped in `<pre></pre>`) with without significantly breaking anything.

**Comment by samsonasik** [comment]
can be closed in favor of https://github.com/zendframework/zend-developer-tools/pull/261
